version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=reclamation
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - 3308:3306
    volumes:
      - ./my-datavolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - myapp-mysql
    environment:
      PMA_HOST: myapp-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80   
  backend:
    image: reclamation-backend:0.0.8
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8181:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3306
    volumes:
      - ./uploads-files:/uploads
  reclamation_frontend:
    image: reclamation-frontend:0.0.8
    links:
      - "backend"
    depends_on:
      - "backend"
    ports:
      - "8012:80"
