version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=reclamation
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - 3308:3306
    volumes:
      - ./my-datavolume:/var/lib/mysql

  backend:
    image: zahrabrahim/reclamation-backend:0.0.1
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8181:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3306
    volumes:
      - ./uploads-files:/uploads
  reclamation_frontend:
    image: zahrabrahim/reclamation-frontend:0.0.1
    links:
      - "backend"
    depends_on:
      - "backend"
    ports:
      - "8012:80"
